remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Antonio Barbalau
description: Machine Learning Researcher
logo: logo.png
show_downloads: false
github:
  is_user_page: false