remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme

title: Antonio Barbalau
description: Machine Learning Researcher @ <a href="https://bit-ml.github.io/">Bitdefender</a><br/>Scientific Committee Member @ <a href="https://olimpiada-ai.ro//">AI Olympiad, Romania</a><br/><a href="https://scholar.google.com/citations?user=EzY9Q7YAAAAJ">Google Scholar</a> Profile
logo: profile_picture.png
show_downloads: false
github:
  is_user_page: false
